### ISSUE TITLE
OpenIDConnect::API:VERSION doesn't autoload

### ISSUE THREAD

**Issue by johnkolen** [paypal/PayPal-Ruby-SDK#92] opened 2015-02-08 18:57 UTC
```ruby
require 'paypal-sdk-rest'
puts PayPal::SDK::REST::VERSION
#PayPal::SDK::OpenIDConnect::API::VERSION = PayPal::SDK::REST::VERSION
puts PayPal::SDK::OpenIDConnect::API.user_agent
```
Above code fragment fails with
1.1.1
/usr/local/rvm/gems/ruby-2.1.2/gems/paypal-sdk-rest-1.1.1/lib/paypal-sdk/core/openid_connect/api.rb:42:in `user_agent': uninitialized constant Class::VERSION (NameError)
	from lib/paypal.rb:6:in `<main>'

Remove the comment symbol and it works as expected.
1.1.1
PayPalSDK/openid-connect-ruby 1.1.1 (paypal-sdk-core 1.1.1; ruby 2.1.2p95-x86_64-linux)

**Comment by jziaja** [comment] 2015-02-09 15:44
`PayPal::SDK::OpenIDConnect::API.user_agent` [references](https://github.com/paypal/PayPal-Ruby-SDK/blob/master/lib/paypal-sdk/core/openid_connect/api.rb#L42) the `VERSION` property assuming it's part of a known namespace (which is how the SDK was designed).  In order for this to work, you'll need to add the following `include` directive so the properties and classes defined in the `PayPal::SDK::REST` module are visible in the current namespace:

````ruby
include PayPal::SDK::REST
````

**Comment by jziaja** [comment] 2015-02-09 16:36
Upon further inspection, it looks like the code should probably be changed so the `include` directive isn't required.  Changing the following line in [`lib/paypal-sdk/core/openid_connect/api.rb`](https://github.com/paypal/PayPal-Ruby-SDK/blob/v1.1.1/lib/paypal-sdk/core/openid_connect/api.rb#L42) will allow the above code fragment to work without needing the additional `include`:

**Current Code**
````ruby
class << self
  def user_agent
    @user_agent ||= "PayPalSDK/openid-connect-ruby #{VERSION} (#{sdk_library_details})"
  end
end
````

**Proposed Change**
````ruby
class << self
  def user_agent
    @user_agent ||= "PayPalSDK/openid-connect-ruby #{PayPal::SDK::REST::VERSION} (#{sdk_library_details})"
  end
end
````

My guess is this is a result of merging the **core** SDK into this repo.  The current code is intentionally written to be flexible so other SDKs can specify whatever `VERSION` property they want and this class will pick it up automatically.  However, that's no longer needed in this SDK.

**Comment by jziaja** [comment] 2015-04-07 14:11
This should be resolved in the latest version thanks to the PR from @jwilsjustin.  Please reopen if you still encounter this problem. Thanks!

**Closed by jziaja** 2015-04-07 14:11 UTC
Labels: enhancement
