### ISSUE TITLE
Refunds not working in sandbox

### ISSUE THREAD

**Issue by noctivityinc** [paypal/PayPal-Ruby-SDK#343] opened 2018-04-07 15:08 UTC
### General information

* SDK/Library version: paypal-sdk-rest (1.7.2)
* Environment: sandbox
* `PayPal-Debug-ID` values: ?
* Language, language version, and OS: local dev on OSX

### Issue description

We are using the Express Checkout javascript to complete a sale and then storing that sale ID so that we can refund it later if needed.  All that works fine, except while testing in the sandbox we *cannot* get refunds to work.  We get an INTERNAL SERVICE ERROR everytime, regardless of the sale we try to refund.

Here is what we are seeing:

```
 => "1W3642558A725172W"
2.4.3 :024 > sale = pp::Sale.find(id)
I, [2018-04-07T11:01:28.996946 #83307]  INFO -- : Request[get]: https://api.sandbox.paypal.com/v1/payments/sale/1W3642558A725172W
D, [2018-04-07T11:01:28.997009 #83307] DEBUG -- : Request.body=null	request.header={"Authorization"=>"Bearer A21AAFNM9Cxq1y-Te6xh7cEhitWNOsb3HuoXqhyZ1lP147mm-7YZs8pGmlZGZFfgxLZiNEcxYSBxEYvUPY_2Cv2QWG4Sd9FTg", "Content-Type"=>"application/json", "User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.7.2 (paypal-sdk-core 1.7.2; ruby 2.4.3p205-x86_64-darwin17;OpenSSL 1.1.0g  2 Nov 2017)"}
I, [2018-04-07T11:01:29.620529 #83307]  INFO -- : Response[200]: OK, Duration: 0.623s
D, [2018-04-07T11:01:29.620619 #83307] DEBUG -- : Response.body={"id":"1W3642558A725172W","state":"completed","amount":{"total":"7.96","currency":"USD","details":{"subtotal":"7.96"}},"payment_mode":"INSTANT_TRANSFER","protection_eligibility":"ELIGIBLE","protection_eligibility_type":"ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE","transaction_fee":{"value":"0.53","currency":"USD"},"invoice_number":"","parent_payment":"PAY-12550921406850413LLENRGY","create_time":"2018-04-07T14:43:09Z","update_time":"2018-04-07T14:43:09Z","links":[{"href":"https://api.sandbox.paypal.com/v1/payments/sale/1W3642558A725172W","rel":"self","method":"GET"},{"href":"https://api.sandbox.paypal.com/v1/payments/sale/1W3642558A725172W/refund","rel":"refund","method":"POST"},{"href":"https://api.sandbox.paypal.com/v1/payments/payment/PAY-12550921406850413LLENRGY","rel":"parent_payment","method":"GET"}]}	Response.header={"date"=>["Sat, 07 Apr 2018 15:01:29 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["2f9dadcb6a1b8", "2f9dadcb6a1b8"], "content-language"=>["*"], "http_x_pp_az_locator"=>["sandbox.slc"], "set-cookie"=>["X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D1239271514%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Sat, 07 Apr 2018 15:31:29 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["831"], "connection"=>["close"], "content-type"=>["application/json"]}
 => #<PayPal::SDK::REST::DataTypes::Sale:0x00007fcbbab091d0 @error=nil, @id="1W3642558A725172W", @state="completed", @amount=#<PayPal::SDK::REST::DataTypes::Amount:0x00007fcbbab09068 @error=nil, @total="7.96", @currency="USD", @details=#<PayPal::SDK::REST::DataTypes::Details:0x00007fcbbab08f00 @error=nil, @subtotal="7.96">>, @payment_mode="INSTANT_TRANSFER", @protection_eligibility="ELIGIBLE", @protection_eligibility_type="ITEM_NOT_RECEIVED_ELIGIBLE,UNAUTHORIZED_PAYMENT_ELIGIBLE", @transaction_fee=#<PayPal::SDK::REST::DataTypes::Currency:0x00007fcbbab08c80 @error=nil, @value="0.53", @currency="USD">, @parent_payment="PAY-12550921406850413LLENRGY", @create_time="2018-04-07T14:43:09Z", @update_time="2018-04-07T14:43:09Z", @links=[#<PayPal::SDK::REST::DataTypes::Links:0x00007fcbbab08668 @error=nil, @href="https://api.sandbox.paypal.com/v1/payments/sale/1W3642558A725172W", @rel="self", @method="GET">, #<PayPal::SDK::REST::DataTypes::Links:0x00007fcbbab083e8 @error=nil, @href="https://api.sandbox.paypal.com/v1/payments/sale/1W3642558A725172W/refund", @rel="refund", @method="POST">, #<PayPal::SDK::REST::DataTypes::Links:0x00007fcbbab081b8 @error=nil, @href="https://api.sandbox.paypal.com/v1/payments/payment/PAY-12550921406850413LLENRGY", @rel="parent_payment", @method="GET">]>
2.4.3 :025 > sale.refund({})
I, [2018-04-07T11:01:46.463982 #83307]  INFO -- : PayPal-Request-Id: ae8a19fb-e0c3-45b7-bcce-c912581e0722
I, [2018-04-07T11:01:46.466764 #83307]  INFO -- : Request[post]: https://api.sandbox.paypal.com/v1/payments/sale/1W3642558A725172W/refund
D, [2018-04-07T11:01:46.469322 #83307] DEBUG -- : Request.body={}	request.header={"Authorization"=>"Bearer A21AAFNM9Cxq1y-Te6xh7cEhitWNOsb3HuoXqhyZ1lP147mm-7YZs8pGmlZGZFfgxLZiNEcxYSBxEYvUPY_2Cv2QWG4Sd9FTg", "Content-Type"=>"application/json", "User-Agent"=>"PayPalSDK/PayPal-Ruby-SDK 1.7.2 (paypal-sdk-core 1.7.2; ruby 2.4.3p205-x86_64-darwin17;OpenSSL 1.1.0g  2 Nov 2017)", "PayPal-Request-Id"=>"ae8a19fb-e0c3-45b7-bcce-c912581e0722"}
I, [2018-04-07T11:01:49.412429 #83307]  INFO -- : Response[500]: Internal Server Error, Duration: 2.936s
W, [2018-04-07T11:01:49.413461 #83307]  WARN -- : Response.body={"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error occurred.","information_link":"https://developer.paypal.com/docs/api/payments/#errors","debug_id":"6b52875bce3a0"}	Response.header={"date"=>["Sat, 07 Apr 2018 15:01:46 GMT"], "server"=>["Apache"], "paypal-debug-id"=>["6b52875bce3a0", "6b52875bce3a0"], "content-language"=>["*"], "connection"=>["close"], "http_x_pp_az_locator"=>["sandbox.slc"], "set-cookie"=>["X-PP-SILOVER=name%3DSANDBOX3.API.1%26silo_version%3D1880%26app%3Dapiplatformproxyserv%26TIME%3D1524484186%26HTTP_X_PP_AZ_LOCATOR%3Dsandbox.slc; Expires=Sat, 07 Apr 2018 15:31:49 GMT; domain=.paypal.com; path=/; Secure; HttpOnly", "X-PP-SILOVER=; Expires=Thu, 01 Jan 1970 00:00:01 GMT"], "vary"=>["Authorization"], "content-length"=>["184"], "content-type"=>["application/json"]}
PayPal::SDK::Core::Exceptions::ServerError: Failed.  Response code = 500.  Response message = Internal Server Error.  Response debug ID = 6b52875bce3a0, 6b52875bce3a0.
```

**Comment by xiaoleih41** [comment] 2018-04-09 17:11
The transaction was refunded on Apr 7, 2018 08:14:53 PDT.

**Comment by xiaoleih41** [comment] 2018-04-13 16:28
Close this issue as the cause has been given.

**Closed by xiaoleih41** 2018-04-13 16:28 UTC
