### ISSUE TITLE
reauthorize fails because of details in amount

### ISSUE THREAD

**Issue by mraidel** [paypal/PayPal-Ruby-SDK#232] opened 2016-09-08 13:33 UTC
### General Information
- Mode (Sandbox/Live): Sandboy
- Version of Ruby used: 2.1.9
- SDK Version: 1.4.9
### Issue Description

PayPal::SDK::REST::DataTypes::Authorization#reauthorize generally fails for me with "Amount object in this resource type must not include amount details.". This is because the stored amount looks like this:

```
"amount":{"currency":"EUR","total":"24.90","details":{"subtotal":"24.90"}}
```

If I just remove the additional information it works. `self.amount.details = nil`

**Comment by mraidel** [comment] 2016-09-08 13:51
looking at the sample (https://github.com/paypal/PayPal-Ruby-SDK/blob/master/samples/authorization/reauthorize.rb) it seems to be encouraged to just set the amount again (even though it is already there in the authorization object): 

```
@authorization = Authorization.find("7GH53639GA425732B")
  
  @authorization.amount = {
      :currency => "USD",
      :total => "7.00" };
```

**Comment by Kitton** [comment] 2017-02-21 16:17
The same happens with `Order#authorize`, so it's still relevant and probably @mraidel you can reopen the issue, cause there's a way around, but it's still there

**Comment by mraidel** [comment] 2017-02-22 09:53
@Kitton ok, so I reopen it and we let a contributor decide if they consider it a bug. It is certainly inconvenient and requires additional code to work around.

**Comment by pp-randy** [comment] 2017-02-22 15:51
Thanks for providing a solution.  Would either of you be interested in submitting a pull request?  If not, that is okay and I will follow up further.

**Comment by jaypatel512** [comment] 2018-01-11 20:07
@mraidel @Kitton ! PayPal APIs are open, and can be directly called via CURL request or via our SDKs. To keep SDK operations transparent, we try not to change any behavior of a given API. In this case, the issue is that the API request does not accept `details` as a part of `amount`. The exception thrown back is given from server. Masking this exception by automatically removing `details` inside the SDK will create confusion to developers who are trying to pass that value explicitly and expecting a certain behavior. This also causes issues if in future API allows details object to be passed, causing older integration to suddenly see different behavior from that API, causing a backward incompatible change. 

I think the error thrown is correct, and could be rephrased to make it even more obvious, but adding such logic, even though a simple one liner, can cause much more confusion to external developers. I am going to close this issue for now, but feel free to post a comment if this does not explain your concerns properly, or you have a proposal that can be used instead.

**Closed by jaypatel512** 2018-01-11 20:07 UTC
Labels: sdk-bug
