### ISSUE TITLE
Payment with non US currencies are not working

### ISSUE THREAD

**Issue by yoonwaiyan** [paypal/PayPal-Ruby-SDK#99] opened 2015-03-03 11:29 UTC
I've tried to charge a user by credit card using Payment method, but it seems like the system does not accept currency other than USD. I've tried on MYR and SGD and both payments are failed but payment with USD works. Is there any limitation on credit card charging where cards can be charged based on the card issuance country? Is there any inner problem with the API?

This is my Payment request to charge a credit card in MYR:
```ruby```
        payment = Paypal::Payment.new({
        :intent => "sale",
        :payer => {
          :payment_method => "credit_card",
          funding_instruments:[
            {
              credit_card_token:{
                credit_card_id: card_num,
                payer_id: email
              }
            }]
        },
        :transactions => [{
          :amount => {
            :total => "3.00",
            :currency => "MYR" },
          :description => "Monthly Payment for invoice 54f5902f596f6f5c29200000" }]})
```

And this is the reply i received. Note that I've hidden the card ID and payer_id. This card ID is registered as a test credit card from a paypal sandbox account.
```ruby```
#<PayPal::SDK::REST::DataTypes::Payment:0x007fdcfb2036d8 @error={"name"=>"UNKNOWN_ERROR", "message"=>"An unknown error has occurred", "information_link"=>"https://developer.paypal.com/webapps/developer/docs/api/#UNKNOWN_ERROR", "debug_id"=>"ca8fef8663948"}, @intent="sale", @payer=#<PayPal::SDK::REST::DataTypes::Payer:0x007fdcfb203520 @error=nil, @payment_method="credit_card", @funding_instruments=[#<PayPal::SDK::REST::DataTypes::FundingInstrument:0x007fdcfb20f140 @error=nil, @credit_card_token=#<PayPal::SDK::REST::DataTypes::CreditCardToken:0x007fdcfb20f050 @error=nil, @credit_card_id="CARD-XXXXXXXXXXXXXXXXXXXXXXX", @payer_id="someone@gmail.com">>]>, @transactions=[#<PayPal::SDK::REST::DataTypes::Transaction:0x007fdcfb20ebf0 @error=nil, @amount=#<PayPal::SDK::REST::DataTypes::Amount:0x007fdcfb20eb50 @error=nil, @total="3.00", @currency="MYR">, @description="Monthly Payment for invoice 54f5902f596f6f5c29200000">], @request_id="19464282-53b7-4049-a4b2-307f5eeb0df9", @header={}>
```

**Comment by lws68825** [comment] 2015-03-03 15:08
Hi, @yoonwaiyan . Maybe you should read this documentation, https://developer.paypal.com/webapps/developer/docs/integration/direct/rest_api_payment_country_currency_support/#direct-credit-card-payments

**Comment by jziaja** [comment] 2015-03-03 15:47
Hi @yoonwaiyan , thanks for reporting this issue!  I was able to reproduce this error using a vaulted credit card along with an unsupported currency (as @lws68825 pointed out - thanks!):

![image](https://cloud.githubusercontent.com/assets/8227966/6465941/e45ddc5a-c189-11e4-9633-adb98615240c.png)

I'm guessing what should be returned in this case is the error you get when you provide new credit card details:

![image](https://cloud.githubusercontent.com/assets/8227966/6465966/0d10a4b6-c18a-11e4-9716-20939eccad28.png)

I've reported this issue internally (ticket# **PPTIPS-2908**), and will followup with you here once I have a response from the payments team.

**Comment by jziaja** [comment] 2015-03-03 17:14
Quick update regarding credit card payments using unsupported currencies.  I'm seeing the following errors being returned:

| Currency | Funding Source | API Error |
| ----------- | --------------------- | ------------ |
| `SGD` | `credit_card` | `UNKNOWN_ERROR` |
| `SGD` | `credit_card_token` | `UNKNOWN_ERROR` |
| `MYR` | `credit_card` | `VALIDATION_ERROR` |
| `MYR` | `credit_card_token` | `UNKNOWN_ERROR` |

I've been informed that a possible reason the `MYR` currency is returning a slightly different result for the `credit_card_token` case is that since it is considered an 'in-country' currency, it's likely hitting a payment filter earlier on in the validation process.  I've updated the internal ticket with this information so the payments team knows different currency types are resulting in slightly different API error behavior.

**Comment by ppmtscory** [comment] 2015-09-28 19:44
Closing as internal ticket has been fixed.  Unsupported currencies should now return a CURRENCY_NOT_SUPPORTED error message appropriately.

**Closed by ppmtscory** 2015-09-28 19:44 UTC
Labels: api-bug, api-payments
