### ISSUE TITLE
Getting no batch_id when creating a batch

### ISSUE THREAD

**Issue by heaven** [paypal/PayPal-Ruby-SDK#324] opened 2017-11-28 16:14 UTC
Gem version: 1.6.1

Hi, we do the following:

```ruby
paypal_payout = ::PaypalPayout.find(paypal_payout_id)

paypal_payout.with_lock do
  return if paypal_payout.batch_id.present?

  payout = ::PayPal::SDK::REST::Payout.new({
    :sender_batch_header => {
      :sender_batch_id => SecureRandom.hex(8),
      :email_subject   => paypal_payout.payoutable.subject
    },
    :items               => [{
      :recipient_type => 'EMAIL',
      :amount         => {
        :value    => paypal_payout.amount,
        :currency => paypal_payout.currency
      },
      :note           => paypal_payout.description,
      :receiver       => paypal_payout.payoutable.payout_method.paypal_account.email,
      :sender_item_id => paypal_payout.id
    }]
  })

  batch = payout.create

  paypal_payout.update_attributes!(:batch_id => batch.batch_header.payout_batch_id, :job_id => nil)
  paypal_payout.submitted!
end
```

And this line returns nil `batch.batch_header.payout_batch_id`. No errors raised. We have an email address that constantly leads to this issue, others work well.

**Comment by xiaoleih41** [comment] 2017-11-30 20:34
Are you saying it only happens to one PayPal email? Is this a production issue or sandbox issue. I would suggest you to contact www.paypal-techsupport.com if it's an account specific issue.

**Comment by pp-randy** [comment] 2017-12-13 15:30
Closing due to inactivity

**Comment by heaven** [comment] 2017-12-13 15:43
Hi, sorry missed your reply. We figured out this happened due to doo long `email_subject` field. I think there was an API error so the behavior is definitely wrong, instead of an empty `batch_id` I would expect the gem raising an error.

**Comment by pp-randy** [comment] 2017-12-13 17:02
Ok thank you for the information.  I will reopen so we can look further.

**Comment by xiaoleih41** [comment] 2018-01-09 14:45
Can you reproduce the error and provide a debug ID?

**Comment by pp-randy** [comment] 2018-01-24 15:36
I tested looks to be returning a correct error.  Closing for now, unless you can help us reproduce.

```
{"name":"VALIDATION_ERROR","message":"Invalid request - see details.","debug_id":"caea3b828ce1b","information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors","details":[{"field":"sender_batch_header.email_subject","issue":"Value too long (max length 255)"}]}
```

**Closed by pp-randy** 2018-01-24 15:36 UTC
