### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by JLinares85** [paypal/PayPal-Ruby-SDK#227] opened 2016-08-23 22:17 UTC
When I try to pay with a credit card in live, paypal return me this error

- Mode (Sandbox/Live): Live
- PayPal-Debug-ID(s) (from any logs): d39393b75437
- Version of Ruby used:
- SDK Version: 23

That is the info

Metadata: 

"url": "/v1/payments/payment",
	"create_time": "2016-08-23T22:01:32Z",
	"additional_properties": {},
	"account_number": "1560091313776748170",
	"client_id": "XXXXX",
	"id": "57bcc7bcf8618f1026549246"

Request:

"body": {
		"intent": "sale",
		"payer": {
			"payment_method": "credit_card",
			"funding_instruments": [
				{
					"credit_card": {
						"expire_year": 2020,
						"type": "visa",
						"number": "xxxxxxxxxxxx7640",
						"expire_month": 8,
						"cvv2": "***"
					}
				}
			]
		},
		"transactions": [
			{
				"amount": {
					"currency": "USD",
					"total": "24.89"
				},
				"description": "08231615"
			}
		]
	},
	"header": {
		"content-length": "279",
		"via": "1.1 v1-akamaitech.net(ghost) (AkamaiGHost), 1.1 akamai.net(ghost) (AkamaiGHost)",
		"accept": "application/json",
		"x-pp-corrid": "d39393b75437",
		"pp_remote_addr": "74.92.68.113",
		"x-pp-ads-performed": "false",
		"paypal-request-id": "db9176f7-01a7-4d03-af93-6da950a572a8",
		"user-agent": "PayPalSDK/PayPal-Android-SDK 2.10.0 (Android 5.0.2; samsung SM-T357T; )",
		"paypal-item-id": "adde15da86a6bc027eee97cdcabfb5c835ad6d6b",
		"x-akamai-config-log-detail": "true",
		"cache-control": "no-cache, max-age=0",
		"te": "chunked;q=1.0",
		"authorization": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxGxs0",
		"cookie2": "X-PP-SILOVER=name%3DLIVE5.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D650624087%26HTTP_X_PP_AZ_LOCATOR%3Ddcg12.slc",
		"accept-encoding": "gzip",
		"akamai-x-forwarded-for-7": "74.92.68.113",
		"x-forwarded-for": "74.92.68.113, 184.29.107.13",
		"paypal-client-metadata-id": "338f7da136aa43a78597b698e9dbd1e0",
		"host": "api-m.paypal.com",
		"cookie": "X-PP-SILOVER=name%3DLIVE5.API.1%26silo_version%3D880%26app%3Dplatformapiserv%26TIME%3D650624087%26HTTP_X_PP_AZ_LOCATOR%3Ddcg12.slc",
		"x-slr-orig-script_uri": "https://api.paypal.com/v1/payments/payment",
		"pragma": "no-cache",
		"akamai-origin-hop": "2",
		"pp_geo_loc": "US",
		"x-pp-silover": "name=LIVE5.API.1&silo_version=880&app=platformapiserv&TIME=3167206487&HTTP_X_PP_AZ_LOCATOR=",
		"client-auth": "No cert",
		"connection": "TE, keep-alive",
		"x-edgeconnect-session-id": "4a66d11757bcc7bc357e977",
		"x-pp-slingshot-targetapp": "platformapiserv",
		"content-type": "application/json"
	},
	"additional_properties": {},
	"method": "POST"
}

Response:

"status": 500,
	"duration_time": 41,
	"body": {
		"message": "An internal service error occurred.",
		"information_link": "https://developer.paypal.com/webapps/developer/docs/api/#INTERNAL_SERVICE_ERROR",
		"name": "INTERNAL_SERVICE_ERROR",
		"debug_id": "d39393b75437"
	},
	"additional_properties": {},
	"header": {
		"Content-Length": "208",
		"Content-Language": "*",
		"X-SLR-RETRY-API": "/v1/payments/payment",
		"X-SLR-RETRY": "500",
		"CORRELATION-ID": "d39393b75437",
		"Date": "Tue, 23 Aug 2016 22:01:32 GMT",
		"Connection": "close",
		"Paypal-Debug-Id": "d39393b75437",
		"PROXY_SERVER_INFO": "host=dcg12javapapi4898.dcg12.slc.paypalinc.com;threadId=342",
		"Content-Type": "application/json"
	}
}

**Comment by pp-randy** [comment] 2016-08-24 13:27
Closing as duplicate of https://github.com/paypal/PayPal-Android-SDK/issues/338

**Closed by pp-randy** 2016-08-24 13:27 UTC
